Update Ledger.ts
Import should be relative because `tsc` can't find the import when cudojs is used as a dependency.

    node_modules/cudosjs/build/ledgers/Ledger.d.ts:2:31 - error TS2307: Cannot find module 'src/proto-signing' or its corresponding type declarations.

    2 import { OfflineSigner } from 'src/proto-signing';